#!/usr/bin/env bash

#TODO: point to primary repo once we're able to push to master
IMAGE=docker.pkg.github.com/jschnurr/cosmos/dockerbuild:latest
export UID=$(id -u)
export GID=$(id -g)

# Uncomment this to build the image (one-time)
# docker build -t $IMAGE -f buildenv/Dockerfile . && \
docker run --rm \
    --user $UID:$GID \
    --tty \
    --interactive \
    --volume "${PWD}":/work \
    $IMAGE "$@"
