#!/usr/bin/env bash

IMAGE=docker.pkg.github.com/jschnurr/cosmos/dockerbuild:latest
export UID=$(id -u)
export GID=$(id -g)

# docker build -t $IMAGE . && \
docker run --rm \
    --user $UID:$GID \
    --tty \
    --interactive \
    --volume "${PWD}":/work \
    $IMAGE "$@"
